CREATE TABLE IF NOT EXISTS `jsh_cashier_settlement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `settlement_no` varchar(50) DEFAULT NULL COMMENT '结算单号',
  `session_id` bigint(20) DEFAULT NULL COMMENT '收银会话id',
  `depot_id` bigint(20) DEFAULT NULL COMMENT '门店id',
  `seat_id` bigint(20) DEFAULT NULL COMMENT '座位/包间id',
  `member_id` bigint(20) DEFAULT NULL COMMENT '会员id(可空)',
  `service_total_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '项目金额合计',
  `product_total_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '产品金额合计',
  `total_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '应收合计(项目+产品-优惠)',
  `real_pay_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '实收合计(支付方式拆分之和)',
  `change_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '找零金额',
  `discount_amount` decimal(24,6) DEFAULT '0.000000' COMMENT '优惠金额(预留)',
  `items_json` longtext COMMENT '结算时的消费明细快照(JSON)',
  `status` varchar(20) DEFAULT 'PAID' COMMENT '状态 PAID/VOID',
  `cashier_user_id` bigint(20) DEFAULT NULL COMMENT '收银员用户id',
  `created_time` datetime DEFAULT NULL COMMENT '创建时间',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '租户id',
  `delete_flag` varchar(1) DEFAULT '0' COMMENT '删除标记，0未删除，1删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_settlement_no` (`tenant_id`,`settlement_no`),
  KEY `idx_session` (`session_id`),
  KEY `idx_depot_time` (`depot_id`,`created_time`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='收银结算单(含支付拆分与票据快照)';

CREATE TABLE IF NOT EXISTS `jsh_cashier_settlement_payment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `settlement_id` bigint(20) DEFAULT NULL COMMENT '结算单id',
  `pay_method` varchar(20) DEFAULT NULL COMMENT '支付方式 CASH/WECHAT/ALIPAY/BANK/CARD/CREDIT',
  `amount` decimal(24,6) DEFAULT '0.000000' COMMENT '金额',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '租户id',
  `delete_flag` varchar(1) DEFAULT '0' COMMENT '删除标记，0未删除，1删除',
  PRIMARY KEY (`id`),
  KEY `idx_settlement` (`settlement_id`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='收银结算-支付方式拆分';

CREATE TABLE IF NOT EXISTS `jsh_invoice_request` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `settlement_id` bigint(20) DEFAULT NULL COMMENT '结算单id',
  `session_id` bigint(20) DEFAULT NULL COMMENT '收银会话id',
  `depot_id` bigint(20) DEFAULT NULL COMMENT '门店id',
  `member_id` bigint(20) DEFAULT NULL COMMENT '会员id(可空)',
  `buyer_type` varchar(10) DEFAULT NULL COMMENT '抬头类型 PERSONAL/COMPANY',
  `buyer_name` varchar(200) DEFAULT NULL COMMENT '抬头名称',
  `tax_no` varchar(100) DEFAULT NULL COMMENT '税号(企业必填)',
  `email` varchar(100) DEFAULT NULL COMMENT '接收邮箱(电子发票)',
  `phone` varchar(30) DEFAULT NULL COMMENT '接收手机号(可选)',
  `invoice_type` varchar(30) DEFAULT 'ELECTRONIC_NORMAL' COMMENT '发票类型 ELECTRONIC_NORMAL/PAPER_NORMAL等',
  `invoice_content` varchar(200) DEFAULT NULL COMMENT '开票内容(默认服务费)',
  `amount` decimal(24,6) DEFAULT '0.000000' COMMENT '开票金额(默认应收)',
  `status` varchar(20) DEFAULT 'PENDING' COMMENT '状态 PENDING/ISSUED/REJECTED/CANCELED',
  `invoice_no` varchar(100) DEFAULT NULL COMMENT '发票号码(回填)',
  `file_url` varchar(500) DEFAULT NULL COMMENT '发票PDF/图片附件(回填)',
  `created_time` datetime DEFAULT NULL COMMENT '申请时间',
  `processed_time` datetime DEFAULT NULL COMMENT '处理时间',
  `processor_user_id` bigint(20) DEFAULT NULL COMMENT '处理人用户id',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint(20) DEFAULT NULL COMMENT '租户id',
  `delete_flag` varchar(1) DEFAULT '0' COMMENT '删除标记，0未删除，1删除',
  PRIMARY KEY (`id`),
  KEY `idx_settlement` (`settlement_id`),
  KEY `idx_depot_time` (`depot_id`,`created_time`),
  KEY `idx_status` (`status`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='发票申请单(足浴店前台采集信息，财务后续回填)';

